### ISSUE TITLE
NameError: uninitialized constant Overclock::Aws::RDS::AWS

### ISSUE THREAD

**Issue by JustLeo** [gosuri/aws-rds-cookbook#24]
I'm getting the following error and I'm not able to find the root cause:

NameError

uninitialized constant Overclock::Aws::RDS::AWS

Cookbook Trace:

/var/chef/cache/cookbooks/aws-rds/libraries/rds.rb:84:in `rds'
/var/chef/cache/cookbooks/aws-rds/libraries/rds.rb:75:in `instance'
/var/chef/cache/cookbooks/aws-rds/providers/default.rb:26:in `load_current_resource'

Resource Declaration:

In /var/chef/cache/cookbooks/AIPL_AAAP/recipes/aws_rds_postgresql.rb

Could you please help?

**Comment by JustLeo** [comment]
Problem resolved
